### ISSUE TITLE
[meta] Checklist for Open Sourcing / Announce

### ISSUE THREAD

**Issue by slack** [deis/steward#23]
This issue is to discuss and track the things we need to do to both open source steward and launch the project.

Ideally, we would have functioning but alpha-quality versions of:
* [x] Steward in Cloud Foundry mode
* [x] Steward in Helm mode (#10)
* Steward in "native" mode (#88):
    * [x] Launch an EC2 instance (or something)
    * [x] Connect to an existing msyql/postgres instance and create a database, username and password

Non-functional stuff:
* [ ] Document Steward design goals
* [ ] Documentation and examples for deploying Steward in Helm and CF modes
* [ ] Compare and contrast between Steward and:
    * [ ] <https://github.com/cncf/servicebroker/>
    * [ ] <https://github.com/sjenning/kubernetes/tree/catalog-apiserver>
* [ ] Early access to `x` people from the Kubernetes community

**Comment by arschles** [comment]
Steward is now open source. Closing
