### ISSUE TITLE
[Meta] Test against the RedisLabs service broker

### ISSUE THREAD

**Issue by arschles** [deis/steward#60]
The broker is open source at https://github.com/RedisLabs/cf-redislabs-broker. I've forked it to https://github.com/arschles/cf-redislabs-broker

This meta issue is for the following:
- [x] Add a dockerfile to my fork and get automated builds working on quay (https://github.com/RedisLabs/cf-redislabs-broker/pull/3)
  - Might also mean some documentation additions
  - PR this work back to the RedisLabs one
- [x] Make the broker configurable via env vars where necessary (https://github.com/RedisLabs/cf-redislabs-broker/pull/3)
- [ ] Run integration tests against this broker

**Comment by arschles** [comment]
Moved to https://github.com/deis/steward-cf/issues/16, closing
